### ISSUE TITLE
Incorrect operating system classifier 'RISC OS'

### ISSUE THREAD

**Issue by gerph** [Shail-Shouryya/save-thread-result#1]
Hiya,

You've assigned the classifier 'Operating System :: RISC OS' to this project on the package repository. It will not work on RISC OS, as the threading system does not work on RISC OS.

At the very least that classifier should be removed from the package.

**Comment by Shail-Shouryya** [comment]
Hey gerph,

Thanks for the feedback! I wasn't actually sure what `RISC OS` was and assumed threading would work since the OS supported python, but I didn't actually check how the OS works. I'll update the classifier in a bit!

Please feel free to add comments below if you find any more mistakes in the classifiers, and I'll update those as well.

**Comment by Shail-Shouryya** [comment]
Updated classifiers available with [Release `0.0.7`](https://github.com/Shail-Shouryya/save-thread-result/releases/tag/v0.0.7)
